from enum import Enum

class UserRole(str, Enum):
    ADMIN = "ADMIN"
    SALES = "SALES"
    SALES_MANAGER = "SALES_MANAGER"
    INVENTORY = "INVENTORY"
    INVENTORY_MANAGER = "INVENTORY_MANAGER"
    SUPPORT = "SUPPORT"
    SUPPORT_MANAGER = "SUPPORT_MANAGER"
    HR = "HR"
    FINANCE = "FINANCE"
    PROJECT_MANAGER = "PROJECT_MANAGER"
    MARKETING = "MARKETING"


class EmploymentType(str, Enum):
    FULL_TIME = "FULL_TIME"
    PART_TIME = "PART_TIME"
    CONTRACT = "CONTRACT"
    INTERN = "INTERN"
    FREELANCE = "FREELANCE"